### ISSUE TITLE
sample can not run

### ISSUE THREAD

**Issue by GengmeiAndroid** [Kelin-Hong/MVVMLight#1]
the log is:
Process: com.kelin.mvvmlight.zhihu, PID: 4824
   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.kelin.mvvmlight.zhihu/com.kelin.mvvmlight.zhihu.MainActivity}: android.view.InflateException: Binary XML file line #26: Error inflating class android.support.design.widget.CollapsingToolbarLayout
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2282)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2340)
       at android.app.ActivityThread.access$800(ActivityThread.java:157)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1247)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:157)
       at android.app.ActivityThread.main(ActivityThread.java:5293)
       at java.lang.reflect.Method.invokeNative(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
       at dalvik.system.NativeStart.main(Native Method)
    Caused by: android.view.InflateException: Binary XML file line #26: Error inflating class android.support.design.widget.CollapsingToolbarLayout
       at android.view.LayoutInflater.createView(LayoutInflater.java:626)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:855)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:751)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
       at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:276)
       at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:261)
       at com.kelin.mvvmlight.zhihu.MainActivity.onCreate(MainActivity.java:34)
       at android.app.Activity.performCreate(Activity.java:5389)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2246)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2340) 
       at android.app.ActivityThread.access$800(ActivityThread.java:157) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1247) 
       at android.os.Handler.dispatchMessage(Handler.java:102) 
       at android.os.Looper.loop(Looper.java:157) 
       at android.app.ActivityThread.main(ActivityThread.java:5293) 
       at java.lang.reflect.Method.invokeNative(Native Method) 
       at java.lang.reflect.Method.invoke(Method.java:515) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081) 
       at dalvik.system.NativeStart.main(Native Method) 
    Caused by: java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.constructNative(Native Method)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
       at android.view.LayoutInflater.createView(LayoutInflater.java:600)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702) 
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:769) 
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:855) 
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:751) 
       at android.view.LayoutInflater.inflate(LayoutInflater.java:498) 
       at android.view.LayoutInflater.inflate(LayoutInflater.java:398) 
       at android.view.LayoutInflater.inflate(LayoutInflater.java:354) 
       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
       at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:276) 
       at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:261) 
       at com.kelin.mvvmlight.zhihu.MainActivity.onCreate(MainActivity.java:34) 
       at android.app.Activity.performCreate(Activity.java:5389) 
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105) 
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2246) 
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2340) 
       at android.app.ActivityThread.access$800(ActivityThread.java:157) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1247) 
       at android.os.Handler.dispatchMessage(Handler.java:102) 
       at android.os.Looper.loop(Looper.java:157) 
       at android.app.ActivityThread.main(ActivityThread.java:5293) 
       at java.lang.reflect.Method.invokeNative(Native Method) 
       at java.lang.reflect.Method.invoke(Method.java:515) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081) 
       at dalvik.system.NativeStart.main(Native Method) 
    Caused by: java.lang.NoSuchMethodError: android.support.v4.graphics.drawable.DrawableCompat.setLayoutDirection
       at android.support.design.widget.CollapsingToolbarLayout.setStatusBarScrim(CollapsingToolbarLayout.java:663)
       at android.support.design.widget.CollapsingToolbarLayout.<init>(CollapsingToolbarLayout.java:197)
       at android.support.design.widget.CollapsingToolbarLayout.<init>(CollapsingToolbarLayout.java:132)
       at java.lang.reflect.Constructor.constructNative(Native Method) 
       at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
       at android.view.LayoutInflater.createView(LayoutInflater.java:600) 
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702) 
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:769) 
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:855) 
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:751) 
       at android.view.LayoutInflater.inflate(LayoutInflater.java:498) 
       at android.view.LayoutInflater.inflate(LayoutInflater.java:398) 
       at android.view.LayoutInflater.inflate(LayoutInflater.java:354) 
       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
       at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:276) 
       at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:261) 
       at com.kelin.mvvmlight.zhihu.MainActivity.onCreate(MainActivity.java:34) 
       at android.app.Activity.performCreate(Activity.java:5389) 
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105) 
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2246) 
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2340) 
       at android.app.ActivityThread.access$800(ActivityThread.java:157) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1247) 
       at android.os.Handler.dispatchMessage(Handler.java:102) 
       at android.os.Looper.loop(Looper.java:157) 
       at android.app.ActivityThread.main(ActivityThread.java:5293) 
       at java.lang.reflect.Method.invokeNative(Native Method) 
       at java.lang.reflect.Method.invoke(Method.java:515) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081) 
       at dalvik.system.NativeStart.main(Native Method)

**Comment by Kelin-Hong** [comment]
Resolved！

**Comment by GengmeiAndroid** [comment]
It works，thanks.
